# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.7.0
_src_path: gh:radio-aktywne/template-generic
accountname: radio-aktywne
description: documentation 📄
docs: false
projectname: docs
releases: false
reponame: docs
repourl: https://github.com/radio-aktywne/docs
